{"name": "Проверка логина с неверными данными", "status": "passed", "start": 1729853320545, "stop": 1729853320920, "uuid": "ff25781c-a410-4910-91da-7ed1990ebf17", "historyId": "8f90415445626d367e3fa6e965f85875", "testCaseId": "8f90415445626d367e3fa6e965f85875", "fullName": "tests.test_user_login.TestUserLogin#test_login_with_wrong_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-AMN9CM3"}, {"name": "thread", "value": "9852-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}