{"name": "Проверка логина с неверными данными", "status": "passed", "steps": [{"name": "Генерирует случайного пользователя", "status": "passed", "start": 1730291255595, "stop": 1730291255595}], "start": 1730291255595, "stop": 1730291256001, "uuid": "9c337aee-9d8c-49c1-841c-161ec68234da", "historyId": "8f90415445626d367e3fa6e965f85875", "testCaseId": "8f90415445626d367e3fa6e965f85875", "fullName": "tests.test_user_login.TestUserLogin#test_login_with_wrong_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-AMN9CM3"}, {"name": "thread", "value": "7356-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}