{"name": "Проверка логина с неверными данными", "status": "passed", "start": 1729624132395, "stop": 1729624133113, "uuid": "00726d43-f206-4f28-9c22-fa6b243a1b77", "historyId": "8f90415445626d367e3fa6e965f85875", "testCaseId": "8f90415445626d367e3fa6e965f85875", "fullName": "tests.test_user_login.TestUserLogin#test_login_with_wrong_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-AMN9CM3"}, {"name": "thread", "value": "21364-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}